inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml

inherit_from:
  - node_modules/@prettier/plugin-ruby/rubocop.yml

inherit_mode:
  merge:
    - Exclude

Style/BlockDelimiters:
  Exclude:
    - app/components/induction_summary_component.rb

Style/MethodCalledOnDoEndBlock:
  Exclude:
    - app/components/induction_summary_component.rb

Style/NumericLiterals:
  Exclude:
    - db/schema.rb

AllCops:
  Exclude:
    - config/initializers/devise.rb
