---
:shared:
  :active_storage_blobs:
    - filename
  :active_storage_attachments:
    - name
  :dsi_users:
    - email
    - first_name
    - last_name
  :name_changes:
    - first_name
    - middle_name
    - last_name
  :users:
    - date_of_birth
    - email
    - family_name
    - given_name
    - name
    - trn
    - one_login_verified_name
    - one_login_verified_birth_date
  :search_logs:
    - last_name
    - date_of_birth
  :feedbacks:
    - email
