---
:shared:
  :data_migrations:
    - version
  :sessions:
    - id
    - session_id
    - data
    - created_at
    - updated_at
  :roles:
    - id
    - code
    - enabled
    - created_at
    - updated_at
