---
shared:
  :active_storage_variant_records:
    - id
    - blob_id
    - variation_digest
  :active_storage_blobs:
    - id
    - key
    - filename
    - content_type
    - metadata
    - service_name
    - byte_size
    - checksum
    - created_at
  :active_storage_attachments:
    - id
    - name
    - record_type
    - record_id
    - blob_id
    - created_at
  :date_of_birth_changes:
    - id
    - user_id
    - date_of_birth
    - created_at
    - updated_at
    - reference_number
    - malware_scan_result
  :dsi_users:
    - id
    - email
    - first_name
    - last_name
    - uid
    - created_at
    - updated_at
    - terms_and_conditions_version_accepted
    - terms_and_conditions_accepted_at
  :dsi_user_sessions:
    - id
    - dsi_user_id
    - role_id
    - role_code
    - organisation_id
    - organisation_name
    - created_at
    - updated_at
  :feature_flags_features:
    - id
    - name
    - active
    - created_at
    - updated_at
  :name_changes:
    - id
    - user_id
    - created_at
    - updated_at
    - first_name
    - middle_name
    - last_name
    - reference_number
    - malware_scan_result
  :users:
    - id
    - email
    - created_at
    - updated_at
    - name
    - given_name
    - family_name
    - trn
    - date_of_birth
    - auth_uuid
    - auth_provider
    - one_login_verified_name
    - one_login_verified_birth_date
  :search_logs:
    - id
    - dsi_user_id
    - last_name
    - date_of_birth
    - result_count
    - search_type
    - created_at
    - updated_at
  :console1984_users:
    - id
    - username
    - created_at
    - updated_at
  :console1984_sessions:
    - id
    - reason
    - user_id
    - created_at
    - updated_at
  :console1984_sensitive_accesses:
    - id
    - justification
    - session_id
    - created_at
    - updated_at
  :console1984_commands:
    - id
    - statements
    - sensitive_access_id
    - session_id
    - created_at
    - updated_at
  :audits1984_audits:
    - id
    - status
    - notes
    - session_id
    - auditor_id
    - created_at
    - updated_at
  :feedbacks:
    - id
    - satisfaction_rating
    - improvement_suggestion
    - contact_permission_given
    - email
    - created_at
    - updated_at
    - service
