---
:shared:
  :data_migrations:
    - version
  :sessions:
    - id
    - session_id
    - data
    - created_at
    - updated_at
  :roles:
    - id
    - code
    - enabled
    - internal
    - created_at
    - updated_at
  :bulk_search_responses:
    - id
    - body
    - expires_at
    - dsi_user_id
    - total
    - created_at
    - updated_at
