---
shared:
  :active_storage_variant_records:
    - id
    - blob_id
    - variation_digest
  :active_storage_blobs:
    - id
    - key
    - filename
    - content_type
    - metadata
    - service_name
    - byte_size
    - checksum
    - created_at
  :active_storage_attachments:
    - id
    - name
    - record_type
    - record_id
    - blob_id
    - created_at
  :dsi_users:
    - id
    - email
    - first_name
    - last_name
    - uid
    - created_at
    - updated_at
  :feature_flags_features:
    - id
    - name
    - active
    - created_at
    - updated_at
  :users:
    - id
    - email
    - created_at
    - updated_at
    - name
    - given_name
    - family_name
    - trn
    - date_of_birth
  :search_logs:
    - id
    - dsi_user_id
    - last_name
    - date_of_birth
    - created_at
    - updated_at
  :staff:
    - id
    - email
    - reset_password_sent_at
    - remember_created_at
    - sign_in_count
    - current_sign_in_at
    - last_sign_in_at
    - current_sign_in_ip
    - last_sign_in_ip
    - confirmed_at
    - confirmation_sent_at
    - unconfirmed_email
    - failed_attempts
    - locked_at
    - created_at
    - updated_at
    - invitation_accepted_at
    - invitation_created_at
    - invitation_sent_at
    - invitation_limit
    - invitations_count
    - invited_by_type
    - invited_by_id
  :console1984_users:
    - id
    - username
    - created_at
    - updated_at
  :console1984_sessions:
    - id
    - reason
    - user_id
    - created_at
    - updated_at
  :console1984_sensitive_accesses:
    - id
    - justification
    - session_id
    - created_at
    - updated_at
  :console1984_commands:
    - id
    - statements
    - sensitive_access_id
    - session_id
    - created_at
    - updated_at
  :audits1984_audits:
    - id
    - status
    - notes
    - session_id
    - auditor_id
    - created_at
    - updated_at
  :feedbacks:
    - id
    - satisfaction_rating
    - improvement_suggestion
    - contact_permission_given
    - email
    - created_at
    - updated_at
