---
:shared:
  :active_storage_blobs:
    - filename
  :active_storage_attachments:
    - name
  :dsi_users:
    - email
    - first_name
    - last_name
  :users:
    - date_of_birth
    - email
    - family_name
    - given_name
    - name
    - trn
  :search_logs:
    - last_name
    - date_of_birth
  :staff:
    - email
  :feedbacks:
    - email
    - improvement_suggestion
