default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV.fetch('DATABASE_URL', 'postgres://postgres@localhost:5432') %>

development:
  <<: *default
  database: access_your_teaching_certificates_development

test:
  <<: *default
  database: access_your_teaching_certificates_test

production:
  <<: *default
  database: access_your_teaching_certificates_production
  username: access_your_teaching_certificates
  password: <%= ENV["DATABASE_PASSWORD"] %>
