layout: support_layout
parent_controller: "SupportInterface::SupportInterfaceController"
feature_flags:
  check_service_open:
    author: Felix Clack
    description: Remove the basic authentication when accessing Check a teacher's
      record. This flag should always be inactive on non-production deployments,
      to prevent accidental access by members of the public. Once the service
      goes live, this flag should always be active on production.
  one_login:
    author: Steve Laing
    description: Changes the AYTQ authentication service from Teacher Identity to GOVUK One Login.
      This flag allows us to switch OAuth2 provider, this will impact how users authenticate with the service.
  qualifications_service_open:
    author: Graham Pengelly
    description: Remove the basic authentication when accessing AYTQ.
      This flag should always be inactive on non-production deployments, to
      prevent accidental access by members of the public. Once the service goes
      live, this flag should always be active on production.
  support_service_open:
    author: Felix Clack
    description: Remove the basic authentication when accessing the support
      interface. This flag should always be inactive on non-production
      deployments, to prevent accidental access by members of the public.
      Once the service goes live, this flag should always be active on production.
  manage_roles:
    author: Malcolm Baig
    description: Add a section to the Support interface that allows us to
      manage DSI roles. These are used to authorise access to Check the record
      of a teacher.
  teacher_profile_tags:
    author: Malcolm Baig
    description: Add a profile summary to the teacher show page which contains
      various tags summarising the profile.
  trn_search:
    author: Malcolm Baig
    description: Reduce number of search results shown to users of CTR by prompting
      them for a TRN when last name and date of birth return multiple results.
  malware_scan:
    author: Richard Pattinson
    description: Enable malware scanning
  bulk_search:
    author: Felix Clack
    description: Enable bulk search in Check the record
  downtime_banner:
    author: Richard Pattinson
    description: Display banner informing users of service downtime
