name: Delete Review App on AKS

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  delete-review-app:
    name: Delete Review App ${{ github.event.pull_request.number }}
    concurrency: deploy-review-${{ github.event.pull_request.number }}
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.pull_request.labels.*.name, 'deploy') || contains(github.event.pull_request.labels.*.name, 'deploy-aks') }}
    environment: review

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform-version: 1.6.4
          terraform-wrapper: false

      - uses: DFE-Digital/github-actions/set-kubelogin-environment@master
        with:
          azure-credentials: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Destroy
        run: |
          make ci review terraform-destroy
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}

      - name: Post Pull Request Comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: aks
          message: |
            Review app track and pay deployed to <https://track-and-pay-${{ github.event.pull_request.number }}.test.teacherservices.cloud> was deleted.
            Review app school placements deployed to <https://manage-school-placements-${{ github.event.pull_request.number }}.test.teacherservices.cloud> was deleted.
